name: Cache Test Workflow

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps
          key: cache-93f149c

      - name: prime-cache-93f149c
        run: echo "Cache status: ${{ steps.cache-deps.outputs.cache-hit }}"

